src/Classes.postman_collection.json
src/controllers/admins.js
src/controllers/trainer.js
src/index.js
src/models/Admins.js
src/models/trainer.js
src/routes/index.js
src/routes/trainer.js
src/validations/super-admins.js
src/validations/trainer.js

Request created for Trainer:
Get: to be able to see all the trainers list.
Get by id: to be able to obtain an specific trainer.

BaSP-MR-09-13: Get and get by id trainers

---

src/Classes.postman_collection.json
src/controllers/admins.js
src/routes/admins.js

Implemented the get method, which allows us to fetch the entire list of admins and their respective data. Also implemented the getById method, which allows us to retrieve a specific admin based on their ID

BaSP-MR-09-10: Methods Get & GetByID 

---

src/controllers/admins.js
src/controllers/member.js
src/index.js
src/models/Member.js
src/routes/index.js
src/routes/member.js
src/validations/member.js

BaSP-MR-09-30: Updated member

---

src/controllers/trainer.js
src/routes/trainer.js

Request for create a new trainer user.

BaSP-MR-09-16: Post Trainers

---

src/Classes.postman_collection.json
src/controllers/trainer.js
src/routes/trainer.js

MR-09-17: Delete Trainer

---

src/Classes.postman_collection.json
src/controllers/subscription.js
src/models/Subscription.js
src/routes/index.js
src/routes/subscription.js

An option to obtain a list of subscriptions (GET) or a particular subscription(GET BY ID) was added.

BaSP-MR-09-26: Get & get by id

---

src/controllers/admins.js
src/models/Admins.js
src/routes/admins.js
src/routes/index.js
src/validations/admins.js

The put method to update ADMIN data has been implemented, and the schema has been updated to change the ADMIN data

BaSP-MR-09-12: AdminUpdate

---

src/Classes.postman_collection.json
src/controllers/class.js
src/routes/class.js

The delete method for removing classes by ID has been implemented

BaSP-MR-09-25: Delete Class

---

src/Classes.postman_collection.json
src/controllers/class.js
src/models/Class.js
src/routes/class.js
src/validations/class.js

The put method to update class data has been implemented, and the schema has been updated to change the trainer data from a name to an ID

BaSP-MR-09-23: Update Class

---

src/tests/trainer.test.js

Created test for delete and put request, these tests check different things about requests.

BaSP-MR-64: Created test for delete and put request

---

src/controllers/class.js
src/models/Class.js
src/tests/class.test.js

Add test for put, delete and get all empty from class entity.

BaSP-MR-39: Class tests Put&Delete

---

src/models/Trainer.js
src/validations/trainer.js

BaSP-MR-139: Fix trainer model

---

src/validations/trainer.js

-Fix Joi validation in Trainer resource

BaSP-MR-202: Trainer Joi Validation fix

---

src/controllers/activity.js
src/validations/activity.js

Fixes in controllers of Activities resource. Methods PUT, POST, DELETE html response structure updated

BaSP-MR-204: hot fixes in controller

---

src/controllers/admins.js
src/validations/admins.js

_**Correction of the structure of the responses for admin**_

BaSP-MR-205: fix admins structure of the results

---

src/controllers/admins.js
src/validations/admins.js
src/validations/class.js

The minimum that accepts the validation of classes and some minor changes was modified.

BaSP-MR-218: change joi in classes and validations

---

package-lock.json
package.json
src/helper/firebase/index.js

I installed Firebase and created helper

BaSP-MR-224: Install Firebase in Server

---

.husky/pre-commit
src/controllers/admins.js
src/controllers/auth.js
src/controllers/member.js
src/controllers/super-admin.js
src/controllers/trainer.js
src/helper/firebase/index.js
src/middlewares/authMiddleware.js
src/models/Admins.js
src/models/Member.js
src/models/SuperAdmin.js
src/models/Trainer.js
src/tests/admins.test.js
src/validations/member.js
src/validations/trainer.js

BaSP-MR-226: firebase backend configuration

---

.husky/pre-commit
package.json
src/controllers/activity.js
src/controllers/admins.js
src/controllers/class.js
src/controllers/member.js
src/controllers/subscription.js
src/controllers/super-admin.js
src/controllers/trainer.js
src/validations/activity.js
src/validations/class.js
src/validations/super-admin.js
src/validations/trainer.js

This PR is directly related to ticket MR-203. Changes were made to the messages of all responses to ensure consistency.
Additionally, JEST was disabled due to encountering issues.

BaSP-MR-203: Response messages corrections

---

src/controllers/activity.js
src/controllers/admins.js
src/controllers/class.js
src/controllers/member.js
src/controllers/subscription.js
src/controllers/super-admin.js
src/controllers/trainer.js

BaSP-MR-244: backend methods to async/await promises

---

src/controllers/class.js

This PR is related to TICKET 221. For the resolution it was required to have consistency in the format of the response related to component CLASSES.

BaSP-MR-221: Classes response structure

---

src/middlewares/authMiddleware.js
src/routes/super-admin.js

I made the Import admins validations, Import admins controllers, Import checkAuth middleware and created Admins routes.

BaSP-MR-249: Create super admin routes & imports

---

src/middlewares/authMiddleware.js
src/routes/trainer.js

Import trainers validations
Import all trainers controllers
Import checkAuth middleware
Create Trainers routes.

BaSP-MR-245: trainer routes creation

---

src/routes/super-admin.js

Fixes in controllers for the super admin routes

BaSP- MR-266: routes in super admin fixed

---

src/routes/admins.js

BaSP-MR-245: admin routes creation

---

src/controllers/member.js
src/models/Member.js
src/validations/member.js

- Deleted isActive from the members model
- Deleted isActive JOI validation

BaSP-MR-281: members-model

---

src/controllers/member.js
src/controllers/trainer.js
src/validations/member.js

- Fix Trainers delete validation
- Fix Members Model

BaSP-MR-286: Fix Trainers-Members validations

---

src/controllers/subscription.js

I fixed a subscription controller.

BaSP-MR-287: Fix Susbcription controller

---

src/validations/trainer.js

Added 'repeat password' field and its validation.

BaSP-MR-317: validations 

---

src/controllers/member.js
src/controllers/trainer.js

DNI validated in trainer and member.

BaSP-MR-307: validate if dni was registered

---

src/validations/trainer.js

BaSP-MR-338: hotFix trainer validations

---

src/controllers/admins.js
src/controllers/member.js
src/controllers/trainer.js
src/models/Admins.js
src/models/Member.js
src/models/Trainer.js
src/validations/admins.js
src/validations/member.js
src/validations/trainer.js

I added picture in member, trainer and admin models

BaSP-MR-385: Add img in Member

---

src/controllers/activity.js
src/models/Activity.js
src/validations/activity.js

BaSP-MR-408: picture property added

---

src/validations/activity.js

change length description lenght on validations

BasP-MR-425: more length description
